name: create and publish docker image

on:
  workflow_call:
    inputs:
      directory:
        required: true
        type: string

jobs:
  build-and-push-image:
    runs-on: self-hosted

    permissions:
      contents: read
      packages: write

    env:
      registry: ghcr.io
      image_name: ${{ github.repository }}

    steps:
      - name: clean up github workspace
        uses: docker://ubuntu:latest
        with:
          args: find /github/workspace/. -name . -o -prune -exec rm -rf -- {} +

      - name: checkout repository
        uses: actions/checkout@v3

      - name: get file changes
        id: file-changes
        uses: Ana06/get-changed-files@v2.1.0

      # rebuild Docker container only if specified Dockerfile has changed:
      - name: log in to the container registry
        id: log-in
        if: |
          contains(steps.file-changes.outputs.all , '${{ inputs.directory }}/Dockerfile')
        uses: docker/login-action@v2
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.github_token }}

      - name: extract metadata (tags, labels) for docker
        id: meta
        if: steps.log-in.outcome != 'skipped'
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.registry }}/${{ env.image_name }}

      - name: build and push docker image
        if: steps.meta.outcome != 'skipped'
        uses: docker/build-push-action@v3
        with:
          context: ./${{ inputs.directory }}
          file: ./${{ inputs.directory }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

